### ISSUE TITLE
Cannot compile Comblayer

### ISSUE THREAD

**Issue by Gradientik** [SAnsell/CombLayer#120]
Hello All!

During compilation I have error:

```
home/nick/CombLayer/System/generalProcess/MainProcess.cxx:82:10: fatal error: 'mcnpDefPhysics.h' file not found
#include "mcnpDefPhysics.h"
```

I couldn't find that file in folder named "mcnpProcessInc" on GitHub.

Best regards,
Nikita

**Comment by SAnsell** [comment]
Sorry -- that was my fault . (as usual).

Forgot to add the new files.

Hopefully that works now.

Since it is new directories you are going to have to do a ./CMake.pl -O -g++=g++ or ./CMake.pl -O -g++=clang etc, and then cmake ./ and then make .  (Do a make -jX where X is large : because this change affects Simulation and that class is in everything (nearly).

**Comment by Gradientik** [comment]
Thank you, Stuart!

I compiled file success now!

Best regards,
Nikita
